[fuzz]
runs = 500
max_test_rejects = 65536

[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test'
solc = '0.8.30'
optimizer_runs = 200

remappings = [
    '@openzeppelin=lib/openzeppelin-contracts/contracts',
    '@forge-std=lib/forge-std/src',
    '@contract=src/contracts',
    '@interface=src/interfaces',
    '@library=src/libraries',
    '@test=test'
]

# BlockDAG Network Configurations
[rpc_endpoints]
blockdag_testnet = "https://rpc-testnet.bdagscan.com"
blockdag_local = "http://localhost:8545"

# BlockDAG Deployment Configuration
[blockdag]
testnet_chain_id = 24171

